services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: production
    image: bachynskyialex/ds-backend:${VERSION}

  frontend:
    build:
      context: .  # Ensure build context is correct (root folder)
      dockerfile: docker/frontend/Dockerfile
      target: production
      args:
        NEXT_PUBLIC_CORE_API_ENTRYPOINT: ${NEXT_PUBLIC_CORE_API_ENTRYPOINT}
        CORE_API_ENTRYPOINT: ${CORE_API_ENTRYPOINT}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    image: bachynskyialex/ds-frontend:${VERSION}
