services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: production
    image: bachynskyialex/ds-backend:${VERSION}
    env_file:
      - ./backend/.env.kube

  frontend:
    build:
      context: .  # Ensure build context is correct (root folder)
      dockerfile: docker/frontend/Dockerfile
      target: production
      args:
        NEXT_PUBLIC_CORE_API_ENTRYPOINT: ${NEXT_PUBLIC_CORE_API_ENTRYPOINT}
        CORE_API_ENTRYPOINT: ${CORE_API_ENTRYPOINT}
    image: bachynskyialex/ds-frontend:${VERSION}
    env_file:
      - ./frontend/.env.kube
