services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bachynskyialex/ds-backend:0.0.1

  frontend:
    build:
      context: .  # Ensure build context is correct (root folder)
      dockerfile: docker/frontend/Dockerfile
      target: production
    image: bachynskyialex/ds-frontend:0.0.1
