# Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.db.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-be-secrets
          volumeMounts:
            - name: db-storage
              mountPath: {{ .Values.db.volumeMountPath }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db-pvc

# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      
# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.db.port }}
