namespace: local-ds

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
# Web app configuration
backend:
  image:
    tag: 0.0.1                 # local tag
    pullPolicy: Always

frontend:
  image:
    tag: 0.0.1                 # local tag
    pullPolicy: Always
  env:
    NODE_ENV: production
    
queue:
  image:
    tag: 0.0.1
    pullPolicy: Always
    
cron:
  image:
    tag: 0.0.1
    pullPolicy: Always

letsEncrypt:
  ## Possible values:
  # selfSigned -> self signed certificate issuer suited for local development
  # stage -> use https://acme-staging-v02.api.letsencrypt.org/directory server for issuer, suited for stage environment
  # prod -> use https://acme-v02.api.letsencrypt.org/directory server for issuer, suited for production
  type: selfSigned
  # email in case stage or prod type of issuer is set
  email: example@somemail.com

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  tlsEnabled: true
  host: ds.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - ds.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2
